export const FETCH_SINGLE_CATEGORIES_REQUEST =
	'FETCH_SINGLE_CATEGORIES_REQUEST';
export const FETCH_SINGLE_CATEGORIES_SUCCESS =
	'FETCH_SINGLE_CATEGORIES_SUCCESS';
export const FETCH_SINGLE_CATEGORIES_FAILURE =
	'FETCH_SINGLE_CATEGORIES_FAILURE';
